### PR TITLE
Added functionality for masking and unmasking services

### PR DESCRIPTION
**Pull request by lazarosgogos**
I have included an optional masking/unmasking of services by adding two seperate buttons (one for each).

To enable this, go to the extension's settings and toggle show mask button, as it is disabled by default (I presume not everyone would want this kind of behavior by default).

Any input is welcome ! :)

### CODE REVIEW

**Comment by jonian** [comment]
Hey @lazarosgogos, thank you for the PR! this looks great, except some minor issues, not related to the functionality. I will comment on those lines.

**Comment by jonian** [comment]
Also It would be great if you could check if a service if masked/unmasked and show only 1 button to mask/unmask depending on the current state.

**Comment by lazarosgogos** [comment]
I tried doing that initially, but I hit a wall when trying to get the states of all services and filtering them out, so I chose to do it with a more straight-forward approach.  I will happily give it one more shot though :)

**Comment by jonian** [comment]
One way to get the masked services list is:

```js
// Add this in utils.js
function getMaskedServicesList(type) {
  const args = ['--type=service,timer,mount', '--no-legend', '| grep masked']
  return systemctlList(type, ['list-unit-files', ...args])
}

// Use in extension.js refresh()
const maskStates  = stateTypes.reduce(
  (all, type) => ({ ...all, [type]: getMaskedServicesList(type) }), {}
)

// In extension.js services.forEach
const mask = maskStates[type].includes(service)
```

I hope this helps.

**Comment by lazarosgogos** [comment]
Ok @jonian I have added the toggle button, but there is a slight problem with it, and I have a suspicion for what the root cause is. 

Everytime the panel menu is spawned, there is a slight half-a-second delay. I think it is caused due to fetching all services to see which ones are masked and which are not. Any ideas how to make that faster?

The tool is completely functional otherwise, the only problem is that small delay which can become annoying if the widget is used often.

**Comment by jonian** [comment]
@lazarosgogos I have an idea on how to do it. I think using the command below is faster, the same as `is-active` check:

```
systemctl --system is-enabled service1 service2 service3
```
The command above returns `enabled`, `disabled` and `masked` as states. You can use a function that already exists in utils `getServicesState`, but you have to add a new argument that replaces `is-active`.

```js
// utils.js
function getServicesState(type, flag, services) {
  const res = systemctl(type, [flag, ...services])
  const out = Bytes.toString(res[1])

  return out.split('\n').reduce(
    (all, value, idx) => ({ ...all, [services[idx]]: value }), {}
  )
}

// extension.js
const fetchStates = (type, flag) => Utils.getServicesState(
  type, flag, services.filter(ob => ob.type == type).map(ob => ob.service)
)

const unitStates  = stateTypes.reduce(
  (all, type) => ({ ...all, [type]: fetchStates(type, 'is-active') }), {}
)

const maskedStates  = stateTypes.reduce(
  (all, type) => ({ ...all, [type]: fetchStates(type, 'is-enabled') }), {}
)
```

I can merge the PR and change the masked check, if you want.

**Comment by lazarosgogos** [comment]
No problem, I implemented it myself! Thanks a lot for the help! I believe it's ready for merging :)

**Comment by jonian** [comment]
Looks great @lazarosgogos. Thank you for your contribution!

**Pull request merged**
