### PR TITLE
add support for parameterized services

### PR DESCRIPTION
**Pull request by Haringat**
solves #2.

### CODE REVIEW

**Comment by jonian** [comment]
That was fast @Haringat! I think it would be better to use `trimParameter` inside `isValidService` and `getServiceType` methods to ensure they work the same whenever they are called, like:

```js
isValidService(name) {
  const service = this.trimParameter(name)
  return this.availableServices.all.includes(service)
}

getServiceType(name) {
  const service = this.trimParameter(name)
  
  if (this.availableServices.system.includes(service)) {
    return 'system'
  }

  if (this.availableServices.user.includes(service)) {
    return 'user'
  }
}
```

**Comment by Haringat** [comment]
@jonian Good point. I only wanted to call the method once but having consistency in how `isValidService` and `getServiceType` work, might be more important.

**Comment by Haringat** [comment]
There you go.

**Comment by jonian** [comment]
Thank you for your contribution!

**Pull request merged**
